version: '3.8'
services:
  node-app:
    container_name: new-api-dokliplife
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3055:5001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      # 컨테이너 시스템 시간을 한국 시간(KST, UTC+9)으로 동기화
      - TZ=Asia/Seoul